### ISSUE TITLE
need a sort of unique(kNNnames) in loadKNNspeciesLayers

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/LandR#10]
Line 413 needs to be sorted first or it may potentially mix up species:

```r
names(speciesLayers) <- unique(kNNnames)
```

but should be something like

```r
names(speciesLayers) <- sort(unique(kNNnames))
```

**Comment by achubaty** [comment]
we need to verify the correct behaviour and ensure that sorting matches the order of the layers. this change should definitely be accompanied by unit tests that verify the behaviour.

**Comment by achubaty** [comment]
from Tati: 

>use the `.sort...()` for consistency among OS

**Comment by achubaty** [comment]
any updates on this?

**Comment by CeresBarros** [comment]
No clue, but presumably it's been fixed?

**Comment by achubaty** [comment]
this looks fixed in branch:

```r
  correctOrder <- sapply(unique(kNNnames), function(x) grep(pattern = x, x = targetFiles, value = TRUE))
  names(speciesLayers) <- names(correctOrder)[match(correctOrder, targetFiles)]
```
