### ISSUE TITLE
assertPostFireDist() undefined

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/LandR#101]
```r
FireDisturbancePM: no visible global function definition for
     ‘assertPostFireDist’
   Undefined global functions or variables:
     assertPostFireDist
```

**Comment by achubaty** [comment]
@CeresBarros should this be `assertPostPartialDist` ?

**Comment by CeresBarros** [comment]
Yes it should. I changed the function name and most’ve missed an instance, or accidentally reverted the change somewhere.

Thanks for catching that. I’ll fix when I’m back, unless you want to go ahead.
