### ISSUE TITLE
convertUnwantedLCC throws error when no pixels need to be converted

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/LandR#11]
`out3` object is not produced if `length(theUnwantedPixels)` is 0 to start with. Maybe an empty table should be returned in this case?

**Comment by eliotmcintire** [comment]
Sounds like a plan...

**Comment by CeresBarros** [comment]
just noticed this has been solved before. Sorry

**Comment by CeresBarros** [comment]
False alarm. it was only partially solved. On it

**Comment by CeresBarros** [comment]
solved. b4164c1da045a5c38f86bcb7eb4dbad576168ceb
