### ISSUE TITLE
new LandR assertion failing

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/LandR#21]
on l. 467 of `prepSpeciesLayers.R`this:
`assertthat::assert_that(identical(raster::maxValue(CCstack), rep(10L, nlayers(CCstack))))`
is failing because 
```
raster::maxValue(CCstack)
[1] 10  7 10 10 10
```
Are the max values supposed to be 10, or anything up to 10? (also is 10, 10% cover?)

**Comment by CeresBarros** [comment]
fixed here: cf5b999c07b0fa6c8edc63b6173c952fce4cd4f9

**Comment by achubaty** [comment]
for posterity:

> I hadn’t considered smaller areas might have diff max values. It should be less than or equal to ten then
> 10 means 100% cover; 7 means 70%; etc.
