### ISSUE TITLE
make a "createRTM" funciton 

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/LandR#60]
so that we can stop copy-pasting the steps the RTM across modules.
fucntion needs to get rawBiomassMap if need be

**Comment by achubaty** [comment]
is this still required, or will the new makeRawBiomassMap function suffice for this?

**Comment by CeresBarros** [comment]
this has been fixed already, a function called `prepRasterToMatch` was added in 20e55cc73f0e3e4ca91a21579b368a9c8f18d4d9
