### ISSUE TITLE
vegTypeMapGenerator() fails, missing column totalBiomass

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/LandR#67]
only hitting this error when plotting using `Biomass_speciesData` via `plotVTM()`

**Comment by achubaty** [comment]
although this may also affect LandWeb postprocessing

**Comment by CeresBarros** [comment]
Why would you want to use this function in `Biomass_speciesData`? This module doesn't use `cohortData` so I don't see how you would make the `vegTypeMap`

**Comment by achubaty** [comment]
that's what was being used: https://github.com/PredictiveEcology/Biomass_speciesData/blob/development/Biomass_speciesData.R#L114-L120

you're correct that it doesn't use cohortData... hence the weirdness. trying to track this down.

**Comment by achubaty** [comment]
`plotVTM()` calls `vegTypeMapGenerator()`, which  creates it's own `cohortData` and `pixelGroupMap` from the species cover stack:

```r
vegTypeMapGenerator.RasterStack <- function(x, ..., doAssertion = getOption("LandR.doAssertion", TRUE)) {
  pixelTable <- suppressMessages(makePixelTable(x, printSummary = FALSE, doAssertion = doAssertion))
  cohortTable <- suppressMessages(.createCohortData(pixelTable, rescale = FALSE, doAssertion = doAssertion))
  cohortTable <- cohortTable[cover > 0]
...
````

so obviously this is where something is going awry...

**Comment by CeresBarros** [comment]
I see. My hunch is that we haven't hit it before because most of us rund `Biomass_speciesData` with plotting turned off.
I believe we need to pass a `biomassMap` to `makePixelTable` to make this work, or change the `vegTypeMapGenerator` to do the map based on cover only

**Comment by CeresBarros** [comment]
or, perhaps `preambleVTG` is not adequately detecting that it needs to use `cover`

**Comment by achubaty** [comment]
`rawBiomassMap` is in `.inputObjects` but it's not assigned to `sim` nor is it listed in inputs.

i will fix this

**Comment by CeresBarros** [comment]
because it's only used to generate `rasterToMatch`. It shouldnt be in `sim`

**Comment by CeresBarros** [comment]
I think the fix should be in the `vegTypeMapGenerator` or `preambleVTG`. We shouldn't need a `biomassMap` just to plot species dominance in terms of cover (using `speciesLayers`)

**Comment by achubaty** [comment]
we need objects like `studyAreaLarge` in order to make the biomass map, so it can't be done in `vegTypeMapGenerator` nor `makePixelTable`. i think adding to the module as input makes the most sense, and user can still supply their own, which is even better.

**Comment by CeresBarros** [comment]
my point is that we shouldn't be using biomass _at all_ in this case and that `vegTypeMapGenerator `needs to accomodate only cover data

**Comment by achubaty** [comment]
ultimately the error is triggered early in `vegTypeMapGenerator.RasterStack` by calling `.createCohortData()` -- this is before we get to calling `vegTypeMapGenerator.data.table` which subsequently calls `preambleVTG()`.

So, working through `.createCohortData()`, i am adding checks for the existence of `totalBiomass` and skipping biomass-age imputation if that column not provided.

i'll update you tomorrow when we meet

**Comment by achubaty** [comment]
yup this did the trick
